- name: PyInstaller Action
  uses: Martin005/pyinstaller-action@v1.2.0
  with: 
    spec: '/main.py'
    # path of your requirements.txt file
    requirements: # optional, default is 
    # Options to set for pyinstaller command Ex: options: '--onedir, -F'       (seperated by comma and space)
  - Supported options: Check readme

    options: # optional, default is 
    # specific python version you want to use
    python_ver: # optional, default is 3.10
    # specific python architecture you want to use
    python_arch: # optional, default is x64
    # Path on runner-os, where generated executable files are stored
    exe_path: # optional, default is ./dist
    # If passed, uploads executable artifact  with this name. Else, artifact won't be uploaded.
    upload_exe_with_name: PassGen.Win.x64
          
